### ISSUE TITLE
TimeStamp Option and "append" option for Combomb Log

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#12]
Feature Request:  The "logging" feature is a great addition but I have a couple additional requests for that feature:
1. Have the option to include a Timestamp (taken from the Computer clock) - so it's tagged on every telnet line that comes in.
2. Have the option to append the log to an existing one - rather then always create a new one.

Hope all is going well.

-Werner

**Comment by cdesjardins** [comment]
Werner, I will get into this issue this weekend, things are a bit busy right now, but this sounds like it should be doable.

**Comment by cdesjardins** [comment]
Werner, new version of combomb v2016.332 released with the append option added, I also updated to the latest version of the encryption lib for ssh. 

I will work on the timestamps sometime in the next week or so when I have more time, but I thought this would get you going for now.

**Comment by cdesjardins** [comment]
Werner, I finally released these features v2107-008, let me know if you have any trouble with them.
