### ISSUE TITLE
Keyboard shortcuts for copy, paste, select-all

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#3]
I may be missing something, but don't believe that keyboard short-cuts for copy, paste, select-all are available.  It's not a big thing since you can access with right mouse click - but <ALT>-C and <ALT>-V are common copy / paste shortcuts that frequently get used.

I don't think com programs use <ctrl>-C since it's got other functions.

If these keyboard shortcuts are already available - please advise and close this issue-request.

-Werner

**Comment by cdesjardins** [comment]
Added shift-ctrl-c, and shift-ctrl-v for copy/paste
