### ISSUE TITLE
Run Process Examples (how to use)

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#4]
First - many thanks Chris for your speedy updates to feature requests I've had.  Much appreciated and greatly enhance my usability.
As I'm working more with ComBomb - I wanted to get into the automation features (Run Process).  Sorry to say - but I'm at a loss as to how to get started with that feature.  Do you have any examples that would shed light on how to use the Run Process tool?
I'm a Hardware Engineer - not SW - but am well versed in coding macro's/bash scripts and functions for Linux, Teraterm and other programs.  If you can provide some simple Run Process example('s) - that would set me on the right path.  I'm sure this would benefit other's too.

Thanks again for your excellent support.
-Werner H.

**Comment by cdesjardins** [comment]
Werner, This one should be easy, I did update the ComBomb website a few days ago with a very very quick intro to the Run Process dialog. http://blog.chrisd.info/combomb/ scroll down to the Run Process paragraph and it quickly explains the redirect, and suppress options. Of course it could be a lot more verbose...

Also there is an example included with ComBomb already in the addons directory, there is a python script called savetofile.py. Maybe I will just give a quick rundown of how to run it and what it does, and then maybe you can pick it up from there.

Fire up ComBomb, and connect to a remote target with ssh, telnet, or whatever, once you are connected you can open the Run Process dialog, and in the "Program" edit box you can browse to the python executable (for example c:\python27\python.exe) Then in the "Arguments" edit box type "savetofile.py", and in the Working directory editbox, browse to the ComBomb/addons directory where the savetofile.py script is located.

Then Check the Redirect stdout, and uncheck the other two checkboxes, like so:

![image](https://cloud.githubusercontent.com/assets/1149188/5620836/f3475d62-952f-11e4-9494-91d36cdc1bad.png)


Then Click ok, to run the script, if you look in the ComBomb/addons directory you will see a new file was created, and it will be filled up with all the text that shows up on the screen, and if binary data comes over the line, it will also be sent to the file as raw binary data.

When you want the script to stop just hit the Run Process button again, or close the window.

If you look at the script you can see it just reads stdin, and writes it to a file... 

Let me know if this answers it for you...
