### ISSUE TITLE
Add option to save Combomb I/O to a file (ie. log)

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#6]
I realize you can create a process to save all Text from Combomb, but would request that such a frequent task should be a built-in feature.  I'm thinking you'd have some option to create a "log" (and specify where it's stored) and it would then have a copy of all text to/from Combomb until the log file is closed  (or Combomb itself is closed).
Thanks for considering.
-Werner Hoehenrieder

**Comment by cdesjardins** [comment]
Werner I will indeed add this option, it does occur to me that one may want to run a script for testing or so and capture the output at the same time... Which is not currently possible. I have some other bugs I would like to work out first, but look for this sometime in the next couple of weeks.

**Comment by whoehenrieder** [comment]
Thanks Chris. Running a script and logging concurrently is exactly what I was interested in. 
Thanks as always for your speedy support.   No hurry on this feature request. 
Werner

**Comment by cdesjardins** [comment]
Werner, I have added the built in logging feature in v2015.196. Feel free to give it a whirl, and let me know if you find any issues, I had it running all day today and I didn't notice any problems. 
Thanks,
    Chris D.
