### ISSUE TITLE
Getting interactive MessageBox on Python script with Combomb

### ISSUE THREAD

**Issue by whoehenrieder** [cdesjardins/ComBomb#7]
Chris,
I've been working on an interactive python script to used with Combomb - and come to an issue:

There are times I want to prompt the user for input from the Python script - but I don't want the responses sent to the Telnet connection I'm on.  On example would be something as simple as a "Do you want to continue" message.  
I've been exploring using the Python "MessageBoxA" function (ctypes.windll.user32.MessageBoxA), which shows promise - but also problems.
The main issue I'm having is when I run the python script on ComBomb - it immediately goes to the MessageBoxA routines for some reason (ie. before it runs the other code that may be before it).

Additionally - although MessageBoxA has some nice styles for Yes/No question input - I don't see that I can use it to input a variable value without that being sent to the Combomb connection.  Is there a way to get an input for the script - but not have it go to the Telnet connection?  (ie. an example would be something like entering "how long do you want to run this test (minutes)?"   I want to feed this info to the python script - but not the corresponding telnet connection).

Not sure I've explained this correctly - but any info you have is appreciated.

NOTE:  If you have any other example python scripts used with Combomb  you could share, that would really help.  The savetofile.py gave me a general start in the right direction.

-Werner

**Comment by cdesjardins** [comment]
Werner, This is a slightly different use case than I typically want, I normally write scripts for automated testing, in which case I typically don't have any user input. Normally I use output from the remote end to indicate when to continue as follows:

    #!/usr/bin/env python

    import sys

    def waitForPrompt(prompt):
        while True:
            line = sys.stdin.readline()
            if prompt in line:
                break

    def main(argv):
        for i in range(1, 10):
            print "ls /usr/lib -1"
            sys.stdout.flush()
            waitForPrompt("$")

    if __name__ == "__main__":
        main(sys.argv[1:])


The above script sends output to the remote end (and flushes it to make sure it gets there) then it just waits for the "$" linux prompt before it continues. Let me know if this helps you.

That being said, It should be possible to add a new checkbox to the run process dialog for sending user input to the remote end, or just to the process. However you should be aware that I am quite busy this week, and then I am off to Tiawan on business for 2 weeks this weekend. So I doubt I will be able to get to this until I return.

**Comment by whoehenrieder** [comment]
Chris,
Your example and details helps a lot!  Thank-you.  One thing that should
help is the "flush" so I make sure that info gets there.  I was missing
that point and hope that clears up some of my script execution order
issues.

Your code for "waitForPrompt" is very helpful - it's a more elegant
solution than I'd coded - and more versatile.

As for my particular use case - it's essentially automated, but I give the
user several prompts up front to select various test parameters (ie. such
as test time, number of loops ..etc).  Once I gather this data - then the
telnet session/script continues on without any further user input required.

Don't worry about any changes this week - you have too much on your plate.
Safe travels and hope the trip is productive (maybe you can get in some
sight-seeing too).

All the best.
-Werner

**Comment by cdesjardins** [comment]
Great news, also remember that you can pass command line parameters into the script in the "Arguments" text box on the "Run Process" dialog. Then you can process the command line arguments in python just as you would normally. That could be another way to "select various test parameters" rather than bugging the user (and consequently the remote system) at runtime.
